import { defineType, defineField } from 'sanity'

/**
 * Provenance tracks who produced this content and in what context.
 * Part of the epistemic governance layer — content should carry
 * its own origin story.
 */
export const provenance = defineType({
  name: 'provenance',
  title: 'Provenance',
  type: 'object',
  fields: [
    defineField({
      name: 'author',
      title: 'Author',
      type: 'string',
      description: 'Human author, if applicable.',
    }),
    defineField({
      name: 'generatedBy',
      title: 'Generated By',
      type: 'string',
      description: 'AI agent or tool that produced this content.',
    }),
    defineField({
      name: 'reviewedBy',
      title: 'Reviewed By',
      type: 'string',
      description: 'Who reviewed the content (human or agent).',
    }),
    defineField({
      name: 'context',
      title: 'Context',
      type: 'text',
      rows: 2,
      description: 'What engagement or circumstance produced this content.',
    }),
    defineField({
      name: 'date',
      title: 'Date',
      type: 'date',
    }),
    defineField({
      name: 'confidenceScore',
      title: 'Confidence Score',
      type: 'number',
      description:
        'Self-reported confidence of the generating agent (0–1). Queryable for pipeline gating but not enforced at authoring time.',
      validation: (Rule) => Rule.min(0).max(1),
    }),
  ],
})
